const data = {
    states: [
        "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", 
        "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", 
        "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", 
        "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", 
        "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", 
        "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", 
        "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", 
        "Wisconsin", "Wyoming"
    ],
    documentCategories: [
        { value: "purchase-sale", label: "Purchase and Sale Transactions" },
        { value: "leasing", label: "Leasing Transactions" },
        { value: "property-management", label: "Property Management" },
        { value: "renovations", label: "Renovations and Construction" },
        { value: "financing", label: "Financing and Mortgages" },
        { value: "development", label: "Real Estate Development" },
        { value: "specialized", label: "Other Specialized Real Estate Documents" }
    ],
    documentTypes: {
        'purchase-sale': [
            "Purchase Agreements",
            "Sale Agreements",
            "Option to Purchase Agreements",
            "Letters of Intent (LOI)",
            "Earnest Money Agreements",
            "Addendums and Amendments",
            "Disclosure Statements",
            "Deeds",
            "Title Transfer Documents",
            "Title Insurance Policies",
            "Title Opinion Letters",
            "Real Estate Settlement Statements",
            "Escrow Agreements",
            "Lien Release Documents",
            "Survey Certifications",
            "Bill of Sale",
            "Affidavits of Title",
            "Notices to Seller or Buyer",
            "Assignment of Purchase Agreements",
            "Post-Closing Agreements"
        ],
        'leasing': [
            "Residential Lease Agreements",
            "Commercial Lease Agreements",
            "Ground Lease Agreements",
            "Master Lease Agreements",
            "Sublease Agreements",
            "Lease Option Agreements",
            "Triple Net (NNN) Lease Agreements",
            "Termination of Lease Agreements",
            "Tenant Estoppel Certificates",
            "Notice to Quit or Vacate",
            "Eviction Notices",
            "Rent Increase Notices",
            "Lease Addendums and Riders",
            "Guaranty Agreements",
            "Security Deposit Agreements",
            "Holdover Tenant Agreements",
            "Assignment and Assumption of Lease",
            "Default Notices",
            "Repair and Maintenance Agreements"
        ],
        'property-management': [
            "Property Management Agreements",
            "Rental Application Forms",
            "Lease Renewal Agreements",
            "Termination of Property Management Contracts",
            "Maintenance and Service Contracts",
            "Rules and Regulations for Tenants",
            "Violation Notices",
            "Inspection Reports",
            "Move-In/Move-Out Checklists",
            "Tenant Complaint Forms",
            "Letters of Demand for Rent Payment",
            "Utility Sharing Agreements",
            "Common Area Maintenance (CAM) Agreements"
        ],
        'renovations': [
            "Construction Contracts",
            "Lump-Sum Contracts",
            "Cost-Plus Contracts",
            "Time and Materials (T&M) Contracts",
            "Architectural Services Agreements",
            "Engineering Services Agreements",
            "Change Orders",
            "Contractor Subcontractor Agreements",
            "Performance Bonds",
            "Payment Bonds",
            "Mechanic's Lien Waivers",
            "Notice of Commencement",
            "Notice of Completion",
            "Construction Loan Agreements",
            "Draw Requests",
            "Punch List Agreements",
            "Warranties on Construction Work",
            "Certificates of Substantial Completion",
            "Indemnity Agreements",
            "Insurance Policies and Endorsements"
        ],
        'financing': [
            "Loan Agreements",
            "Mortgage Deeds",
            "Promissory Notes",
            "Deeds of Trust",
            "Loan Modification Agreements",
            "Foreclosure Notices and Agreements",
            "Short Sale Agreements",
            "Assignment of Mortgage",
            "Release of Mortgage",
            "Installment Sale Contracts",
            "Private Financing Agreements",
            "Guarantee Agreements",
            "Loan Workout Agreements",
            "Equity Sharing Agreements",
            "Refinancing Agreements",
            "Seller Financing Documents",
            "Forbearance Agreements"
        ],
        'development': [
            "Development Agreements",
            "Joint Venture Agreements",
            "Zoning and Land Use Applications",
            "Easement Agreements",
            "Subdivision Agreements",
            "Platting Documents",
            "Environmental Impact Statements",
            "Site Plan Approval Applications",
            "Tax Increment Financing (TIF) Agreements",
            "Right of Way Agreements",
            "Restrictive Covenants",
            "Infrastructure Agreements"
        ],
        'specialized': [
            "Easement Agreements",
            "Reciprocal Easement Agreements (REAs)",
            "Utility Easements",
            "Access Easements",
            "Covenants, Conditions, and Restrictions (CC&Rs)",
            "Condominium Declarations",
            "Co-Op Agreements",
            "Homeowners' Association (HOA) Bylaws and Rules",
            "Boundary Line Agreements",
            "Quiet Title Actions",
            "Encroachment Agreements",
            "Deed Restrictions",
            "Transfer on Death Deeds",
            "Life Estate Deeds",
            "Partitions Agreements",
            "Settlement Agreements",
            "Tax Appeals",
            "Real Estate Syndication Documents",
            "1031 Exchange Agreements",
            "Affidavits of Heirship",
            "Power of Attorney for Real Estate",
            "Escrow Instructions",
            "Brokerage Agreements",
            "Confidentiality Agreements"
        ]
    }
}; 