const data = {
    states: [
        "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", 
        "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", 
        "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", 
        "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", 
        "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", 
        "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", 
        "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", 
        "Wisconsin", "Wyoming"
    ],
    documentCategories: [
        { value: "purchase-sale", label: "Purchase and Sale Transaction" },
        { value: "leasing", label: "Leasing Transaction" },
        { value: "property-management", label: "Property Management" },
        { value: "renovations", label: "Renovation and Construction" },
        { value: "financing", label: "Financing and Mortgage" },
        { value: "development", label: "Real Estate Development" },
        { value: "business-entities", label: "LLC and Partnership Document" },
        { value: "specialized", label: "Other Specialized Real Estate Document" }
    ],
    documentTypes: {
        'purchase-sale': [
            "Purchase Agreement",
            "Sale Agreement",
            "Option to Purchase Agreement",
            "Letter of Intent (LOI)",
            "Earnest Money Agreement",
            "Addendum and Amendment",
            "Disclosure Statement",
            "Deed",
            "Title Transfer Document",
            "Title Insurance Policy",
            "Title Opinion Letter",
            "Real Estate Settlement Statement",
            "Escrow Agreement",
            "Lien Release Document",
            "Survey Certification",
            "Bill of Sale",
            "Affidavit of Title",
            "Notice to Seller or Buyer",
            "Assignment of Purchase Agreement",
            "Post-Closing Agreement"
        ],
        'leasing': [
            "Residential Lease Agreement",
            "Commercial Lease Agreement",
            "Ground Lease Agreement",
            "Master Lease Agreement",
            "Sublease Agreement",
            "Lease Option Agreement",
            "Triple Net (NNN) Lease Agreement",
            "Termination of Lease Agreement",
            "Tenant Estoppel Certificate",
            "Notice to Quit or Vacate",
            "Eviction Notice",
            "Rent Increase Notice",
            "Lease Addendum and Rider",
            "Guaranty Agreement",
            "Security Deposit Agreement",
            "Holdover Tenant Agreement",
            "Assignment and Assumption of Lease",
            "Default Notice",
            "Repair and Maintenance Agreement"
        ],
        'property-management': [
            "Property Management Agreements",
            "Rental Application Forms",
            "Lease Renewal Agreements",
            "Termination of Property Management Contracts",
            "Maintenance and Service Contracts",
            "Rules and Regulations for Tenants",
            "Violation Notices",
            "Inspection Reports",
            "Move-In/Move-Out Checklists",
            "Tenant Complaint Forms",
            "Letters of Demand for Rent Payment",
            "Utility Sharing Agreements",
            "Common Area Maintenance (CAM) Agreements"
        ],
        'renovations': [
            "Construction Contracts",
            "Lump-Sum Contracts",
            "Cost-Plus Contracts",
            "Time and Materials (T&M) Contracts",
            "Architectural Services Agreements",
            "Engineering Services Agreements",
            "Change Orders",
            "Contractor Subcontractor Agreements",
            "Performance Bonds",
            "Payment Bonds",
            "Mechanic's Lien Waivers",
            "Notice of Commencement",
            "Notice of Completion",
            "Construction Loan Agreements",
            "Draw Requests",
            "Punch List Agreements",
            "Warranties on Construction Work",
            "Certificates of Substantial Completion",
            "Indemnity Agreements",
            "Insurance Policies and Endorsements"
        ],
        'financing': [
            "Loan Agreements",
            "Mortgage Deeds",
            "Promissory Notes",
            "Deeds of Trust",
            "Loan Modification Agreements",
            "Foreclosure Notices and Agreements",
            "Short Sale Agreements",
            "Assignment of Mortgage",
            "Release of Mortgage",
            "Installment Sale Contracts",
            "Private Financing Agreements",
            "Guarantee Agreements",
            "Loan Workout Agreements",
            "Equity Sharing Agreements",
            "Refinancing Agreements",
            "Seller Financing Documents",
            "Forbearance Agreements"
        ],
        'development': [
            "Development Agreements",
            "Joint Venture Agreements",
            "Zoning and Land Use Applications",
            "Easement Agreements",
            "Subdivision Agreements",
            "Platting Documents",
            "Environmental Impact Statements",
            "Site Plan Approval Applications",
            "Tax Increment Financing (TIF) Agreements",
            "Right of Way Agreements",
            "Restrictive Covenants",
            "Infrastructure Agreements"
        ],
        'business-entities': [
            "LLC Operating Agreements",
            "Partnership Agreements",
            "Articles of Organization",
            "Articles of Incorporation",
            "Membership Interest Purchase Agreements",
            "Buy-Sell Agreements",
            "Member Withdrawal Agreements",
            "Capital Contribution Agreements",
            "Profit Sharing Agreements",
            "Management Agreements",
            "Voting Rights Agreements",
            "Member Resolution Documents",
            "Dissolution Agreements",
            "Transfer of Membership Interest",
            "Subscription Agreements",
            "Private Placement Memorandums",
            "Corporate Bylaws",
            "Meeting Minutes",
            "Shareholder Agreements",
            "Joint Venture Agreements",
            "Limited Partnership Agreements",
            "General Partnership Agreements",
            "Entity Conversion Documents",
            "Merger and Acquisition Agreements"
        ],
        'specialized': [
            "Easement Agreements",
            "Reciprocal Easement Agreements (REAs)",
            "Utility Easements",
            "Access Easements",
            "Covenants, Conditions, and Restrictions (CC&Rs)",
            "Condominium Declarations",
            "Co-Op Agreements",
            "Homeowners' Association (HOA) Bylaws and Rules",
            "Boundary Line Agreements",
            "Quiet Title Actions",
            "Encroachment Agreements",
            "Deed Restrictions",
            "Transfer on Death Deeds",
            "Life Estate Deeds",
            "Partitions Agreements",
            "Settlement Agreements",
            "Tax Appeals",
            "Real Estate Syndication Documents",
            "1031 Exchange Agreements",
            "Affidavits of Heirship",
            "Power of Attorney for Real Estate",
            "Escrow Instructions",
            "Brokerage Agreements",
            "Confidentiality Agreements"
        ]
    }
}; 